### ISSUE TITLE
Opacity in heatmap_display causing improper display of gradCAM for small images(Ex:- CIFAR10)

### ISSUE THREAD

**Issue by ksasi** [sicara/tf-explain#103]
Hi,

It appears the opacity parameter settings in heatmap_display are causing gradCAM to not properly superimpose on original images. This is specifically being seen when using CIFAR10 and small size data sets.

I think the following line needs a review in display.py file for heatmap_display function.

output = cv2.addWeighted(cv2.cvtColor(image, cv2.COLOR_RGB2BGR), 0.7, heatmap, 1, 0)

Thanks and Regards,
Sasikanth

**Comment by RaphaelMeudec** [comment]
Okay, will look into it and probably make it tuneable. Thanks for raising this!

**Comment by RaphaelMeudec** [comment]
The argument `image_weight` has been added to GradCAM so users can set their own superposition value.
