### ISSUE TITLE
Import Error for certain classes

### ISSUE THREAD

**Issue by oke-aditya** [sicara/tf-explain#108]
- Hi. I am trying to import from tf_explain.core.gradients_inputs but facing an error

![image](https://user-images.githubusercontent.com/47158509/71419497-b8c32200-2695-11ea-861e-76e8201d068c.png)

The other imports such as 
`from tf_explain.core.grad_cam import GradCAM
from tf_explain.core.activations import ExtractActivations
`

are working fine.

**Comment by oke-aditya** [comment]
- Error also valid for VanillaGradients methods from tf.core

**Comment by RaphaelMeudec** [comment]
@oke-aditya Thanks for reporting this, will look into it during the week!

**Comment by oke-aditya** [comment]
- Any Updates ?

**Comment by RaphaelMeudec** [comment]
I've made a release, try upgrading to 0.2.0

**Comment by RaphaelMeudec** [comment]
@oke-aditya Can you check with the newer version and tell me if you have any issue?

**Comment by oke-aditya** [comment]
- Yep Resolved now. I have a nice Colab Tutorial taken from your resources.
I Would like to share that to improve docoumentation.

**Comment by oke-aditya** [comment]
- 
[tf_explain.zip](https://github.com/sicara/tf-explain/files/4041734/tf_explain.zip)
