### ISSUE TITLE
name 'GradCAM' is not defined

### ISSUE THREAD

**Issue by ShowTimeJMJ** [sicara/tf-explain#127]
NameError                                 Traceback (most recent call last)
<ipython-input-10-1e4efd9691e0> in <module>
----> 1 explainer = GradCAM()
      2 grid = explainer.explain(data, model, class_index=np.argmax(preds[0]))

NameError: name 'GradCAM' is not defined

**Comment by RaphaelMeudec** [comment]
@ShowTimeJMJ Could you provide a minimal example that raises the error? Which version of tf-explain are you using?

**Comment by rao208** [comment]
@ShowTimeJMJ Maybe you did not import GradCam. Happened with me before.
