### ISSUE TITLE
Got graph disconnected error when using a pre-trained sequential model.

### ISSUE THREAD

**Issue by tohnperfect** [sicara/tf-explain#138]
I have a trained sequential model which composes of a pre-trained headless efficient net and the final layers. The model.summary() look as follows,

```
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
efficientnet-b3 (Model)      (None, 5, 5, 1536)        10783528  
_________________________________________________________________
gap (GlobalMaxPooling2D)     (None, 1536)              0         
_________________________________________________________________
dropout_out (Dropout)        (None, 1536)              0         
_________________________________________________________________
fc_out (Dense)               (None, 1)                 1537      
=================================================================
Total params: 10,785,065
Trainable params: 1,479,937
Non-trainable params: 9,305,128
_________________________________________________________________
```

My efficientnet-b3 model looks like,

```
Model: "efficientnet-b3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 75, 75, 40)   1080        input_1[0][0]                    
__________________________________________________________________________________________________   
.
.
.
__________________________________________________________________________________________________  
add_18 (Add)                    (None, 5, 5, 384)    0           drop_connect_18[0][0]            
                                                                 batch_normalization_73[0][0]     
__________________________________________________________________________________________________
conv2d_103 (Conv2D)             (None, 5, 5, 1536)   589824      add_18[0][0]                     
__________________________________________________________________________________________________
batch_normalization_77 (BatchNo (None, 5, 5, 1536)   6144        conv2d_103[0][0]                 
__________________________________________________________________________________________________
swish_77 (Swish)                (None, 5, 5, 1536)   0           batch_normalization_77[0][0]     
==================================================================================================
Total params: 10,783,528
Trainable params: 1,478,400
Non-trainable params: 9,305,128
__________________________________________________________________________________________________
```

I tried to use core API GradCAM for the trained model as follows,

```
from tf_explain.core.grad_cam import GradCAM
explainer = GradCAM()
img = load_image(img_path) #tf image
data = ([img], None)
explainer.save(grid, ".", "grad_cam.png")
```

which output this error,

`ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_1:0", shape=(None, 150, 150, 3), dtype=float32) at layer "input_1". The following previous layers were accessed without issue: []`

Please note that the model prediction works fine.

Thank you for your help!

**Comment by rao208** [comment]
I faced a similar problem a few days back.  Try this and this worked very well in my case:

**_Change it to the functional model_**

```
x = pre_trained_model.output  #(in your case pre_trained model is efficientnet-b3)
global_average_layer = GlobalAveragePooling2D()(x)
dropout_layer_1 = Dropout(0.50)(global_average_layer)
prediction_layer = Dense(1, activation='sigmoid')(dropout_layer_1)

model = Model(inputs= pre_trained_model.input, outputs=prediction_layer) 
model.summary()
```
Now, train the model and use it for GradCAM. I hope it works for you too. Please do let us know if you find any other solution i.e. a way around for Sequential models.

**Comment by tohnperfect** [comment]
Thank a lot @rao208 

This means creating a model in a functional way before training and train it again, right? 
I will try that and updated here.

I still wonder if the sequential model can be used with TF-explain because I have several trained sequential models to be explored with GradCAM.

**Comment by rao208** [comment]
@tohnperfect 

> This means creating a model in a functional way before training and train it again, right?

Yes, this means creating the classifier part i.e. global average pooling layer and dense layer (as written in my reply above) in a functional way (before training) and train your entire model again. I used VGG16 as my pre-trained model with `include_top=False`. I guess it is okay when the pre-trained model is a sequential model (just try and see if it is okay :) )

> I still wonder if the sequential model can be used with TF-explain because I have several trained sequential models to be explored with GradCAM.

Well, you can use the sequential models with GradCAM, but the problem here is you are using a  pre-trained network without the classifier. When you try to connect this pre-trained network with your classifier, the model is viewed as two separate graphs. That is why you are getting this error.  

When you build a sequential model from scratch, you won't get 'graph disconnected error'. I have used many sequential models that are built from scratch and it works well with GradCAM (tf_explain)

Honestly, I don't think it will make any difference. The way I understood it is, the functional model is used for more complex architecture for example when you have skip connections like in Resnet and Sequential models are used when you have layers after layers i.e. for simpler architecture. If there is any major difference, then I am not aware of that.

**Comment by tohnperfect** [comment]
I got it. Thank! @rao208

**Comment by vscv** [comment]
Thanks @rao208 @tohnperfect It's works.

Here is workable example just for reference.

`
# MobileNetV2
num_classes = 5

inputs = tf.keras.Input(shape=(224, 224, 3))
aug = data_augmentation(inputs)
pre = preprocess_input(aug)

bm_output = base_model(pre, training=False)
gap2d = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
dro = tf.keras.layers.Dropout(0.2)(gap2d)
outputs = tf.keras.layers.Dense(num_classes)(dro)

model = tf.keras.Model(base_model.input, outputs, name='model-re-mbnetv2')
`

`
# ResNet50

num_classes = 5

inputs = tf.keras.Input(shape=(224, 224, 3))
bm_output = base_model(inputs, training=False)
gap2d = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
outputs = tf.keras.layers.Dense(num_classes)(gap2d)

model = tf.keras.Model(base_model.input, outputs, name='model-re-resnet50')
`

The model should looked like this:
`
Model: "model-re-mbnetv2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_74 (InputLayer)           [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_74[0][0]                   
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
__________________________________________________________________________________________________
Conv1_relu (ReLU)               (None, 112, 112, 32) 0           bn_Conv1[0][0]                   
__________________________________________________________________________________________________
expanded_conv_depthwise (Depthw (None, 112, 112, 32) 288         Conv1_relu[0][0]                 
__________________________________________________________________________________________________
expanded_conv_depthwise_BN (Bat (None, 112, 112, 32) 128         expanded_conv_depthwise[0][0]    
__________________________________________________________________________________________________
expanded_conv_depthwise_relu (R (None, 112, 112, 32) 0           expanded_conv_depthwise_BN[0][0] 
__________________________________________________________________________________________________
expanded_conv_project (Conv2D)  (None, 112, 112, 16) 512         expanded_conv_depthwise_relu[0][0
__________________________________________________________________________________________________
expanded_conv_project_BN (Batch (None, 112, 112, 16) 64          expanded_conv_project[0][0]      
...
...
...
dropout_3 (Dropout)             (None, 1280)         0           global_average_pooling2d_21[0][0]
__________________________________________________________________________________________________
dense_31 (Dense)                (None, 5)            6405        dropout_3[0][0]                  
==================================================================================================
Total params: 2,264,389
Trainable params: 6,405
Non-trainable params: 2,257,984
__________________________________________________________________________________________________
`

**Comment by rao208** [comment]
@vscv There are some techniques online to add the additional input layers to the pretrained model (example: [https://stackoverflow.com/questions/59695637/i-am-trying-to-merge-2-pretrained-keras-model-but-failed](url) or [https://stackoverflow.com/questions/40755914/prepending-downsample-layer-to-resnet50-pretrained-model](url))

I tried following as suggested in the answer on Stackoverflow.  If your end goal is to implement GradCam on layers of the pretrained model, then you cannot do so. If you see the output in 

[https://stackoverflow.com/questions/40755914/prepending-downsample-layer-to-resnet50-pretrained-model](url)

you will see that one cannot extract the layers of pretrained models and hence GradCAM cannot be implemented on the new model.

If you find any solution, please post it here. I tried looking everywhere online, but could not figure it out how to add additional input layer and extract the layers of pretrained model. 

Hope this answers your question :)

**Comment by vscv** [comment]
@rao208 Thanks for hit. I revised the statement of problem.

**Comment by movaldivia** [comment]
@rao208 @vscv did you find any solution?

**Comment by vscv** [comment]
> @rao208 @vscv did you find any solution?

The problem has not been resolved. 
My current alternative is to put preprocess and augmentation into tf.data.map instead of adding it to the base_model.
