### ISSUE TITLE
Installation should accept opencv-contrib-python

### ISSUE THREAD

**Issue by bersbersbers** [sicara/tf-explain#142]
```
> pip check
tf-explain 0.2.1 requires opencv-python, which is not installed.
```

But I have `opencv-contrib-python` installed, and everything is working fine. See also https://github.com/aleju/imgaug/issues/473

**Comment by RaphaelMeudec** [comment]
@bersbersbers thanks for pointing out! Would be happy to review a PR for it if you have time to work on it

**Comment by darinmandarin** [comment]
I also have an issue with opencv when importing tf_explain or any of callbacks.

AttributeError: module 'cv2' has no attribute 'COLORMAP_VIRIDIS'. Neither of installed opencv packages work 
(opencv-contrib-python==4.3.0.36
opencv-python==4.3.0.36)

**Comment by RaphaelMeudec** [comment]
I think the problem has been fixed on master already and shipped in the last release. Closing this issue, thanks for opening it!
