### ISSUE TITLE
saved files are .v2 files

### ISSUE THREAD

**Issue by lilianmarey** [sicara/tf-explain#171]
Hi !

I was trying to use tf-explain on my pretrained neural nets, it seems it worked, however, after running my code, the saved files are ".v2" files. I really don't know how to open this type of files, or how to convert it into .png for example.

I wanted to know if getting this type of files was normal, and if it is, how to open it.

Thanks anyway for sharing the library

**Comment by RaphaelMeudec** [comment]
Those are probably tensorboard files. Can you provide which methods/callbacks you're using?

**Comment by lilianmarey** [comment]
I'm using OcclusionSensitivityCallback and IntegratedGradientsCallback, I had .v2 files for both.
Here is also the architecture of my net and the code I ran
![Capture d’écran 2021-07-07 à 15 56 47](https://user-images.githubusercontent.com/68290011/124772054-f320a700-df3b-11eb-8321-52ba0c63ecf5.png)
![Capture d’écran 2021-07-07 à 15 56 40](https://user-images.githubusercontent.com/68290011/124772087-fb78e200-df3b-11eb-8781-a9c84c7af87d.png)

**Comment by RaphaelMeudec** [comment]
All callbacks are made to draw images directly into tensorboard. You have to open a tensorboard with `tensorboard --logdir path_to_logs` and go to the images tab

**Comment by lilianmarey** [comment]
Ok, it worked, thanks a lot !
