### ISSUE TITLE
Are feature such as occlusion analysis included for tabular data?

### ISSUE THREAD

**Issue by amjass12** [sicara/tf-explain#65]
Hello, 

I was just wondering if any of the feature from tf-explain are planned to (or already) apply to tabular data and non-image data? 

sorry if this has been answered, i have not be able to find this answer anywhere. 

thanks.

**Comment by RaphaelMeudec** [comment]
Hi @amjass12, supporting tabular data isn't planned for the moment. [Shap](https://github.com/slundberg/shap) is doing pretty great with numerical values. However, we plan to extend to NLP models in the future (no clear timeline though)

**Comment by amjass12** [comment]
Hi @RaphaelMeudec, 

Thank you very much for clarifying! Yes I have been using Shap values and just looking around for other methods just to see how they compare. 

Thanks again!
