### ISSUE TITLE
ActivationsVisualizationCallback: predictions and filter_display dimension issue.

### ISSUE THREAD

**Issue by Hassanfarooq92** [sicara/tf-explain#68]
Dimension of prediction's output is (number of images, number of classes) while filter_display is looking for a 4D array.

**Comment by RaphaelMeudec** [comment]
The callback is meant for convolutional layers visualisation and you're probably trying to apply it on a dense layer. That's why you're having a shape issue

**Comment by Hassanfarooq92** [comment]
So i should apply it after the activation function of convolution layers.
And ur gradcam gives gpu memory error. I have rtx 2080ti

**Comment by Hassanfarooq92** [comment]
Got the stuff working. Just to let you know if model is being load and modified separately, it might give error of 'graph disconnected', shouldn't be difficult to tackle if it appears up.

**Comment by rao208** [comment]
@Hassanfarooq92 So, should we apply it after the activation function of convolution layers or after the cnn layer(if activation is not defined inside the layer)?
