### ISSUE TITLE
Lucid and your lib, tf-explain

### ISSUE THREAD

**Issue by Uiuran** [sicara/tf-explain#72]
Hi, I Found very interesting your lib and its interpretability approach, with callbacks, what allows for in training/testing interpretations.

Do you know Lucid, from Deep-Dream creators ? 
https://github.com/tensorflow/lucid/

It seems that you two can contribute to each other, i also plan to do something in your direction for the future ... 

thank you (there is mailing list for this type of message ?) sorry if it wasnt  the right place

**Comment by RaphaelMeudec** [comment]
Hi @Uiuran, thanks for pointing the library out! It seems they are more focused on kernel/channel visualizations. Will keep looking at it in the future. 

You can also contact us via tf-explain@sicara.com, I'll add it in the README.

Thanks!
