### ISSUE TITLE
Visualizing Activation Layers

### ISSUE THREAD

**Issue by sidgan** [sicara/tf-explain#74]
Visualizations of the Activation Layers should happen after a convolution layer, and not the activation layer itself. 

In https://github.com/sicara/tf-explain/blob/master/examples/core/activations_visualization.py#L20 

```
 grid = explainer.explain(data, model, ['activation_6'])
```
needs to be replaced by 
```
 grid = explainer.explain(data, model, ['conv_1']) 
```

Happy to send a pull request for the same.

**Comment by RaphaelMeudec** [comment]
It actually depends on whether you define the activation inside the `Conv2D` layer or outside. If you run the below snippet, first conv output is the output of the activation layer. Second one is the output of the convolution itself.

Maybe a more appropriate line would be `grid = explainer.explain(data, model, ['target_layer'])`? What do you think?

**Comment by sidgan** [comment]
Agree with your suggestion.
