### ISSUE TITLE
Unguided Grad CAM

### ISSUE THREAD

**Issue by RaphaelMeudec** [sicara/tf-explain#77]
Atm, guided backpropagation is included in Grad CAM automatically (see [here](https://github.com/sicara/tf-explain/blob/1a75841762985e55abe19107d09279f68f5731c8/tf_explain/core/grad_cam.py#L89)). The objective of this issue is to make optional this behaviour (but selected by default).

## How to do so?

- If you're not at ease with what Guided Backpropagation is, check the Class Activation Maps section in this [article](https://blog.sicara.com/interpretability-deep-learning-models-tensorflow-2-0-7d4ddaa351a3)
- Add a `use_guided` argument (boolean, default value `True`) to the `.explain()` method of Grad CAM
- Pass the argument to the `get_gradients_and_filters()` method
- Compute guidance only is `use_guided is True`
- Add the argument `use_guided` to the corresponding callback, and pass it as argument to the `explain()` method
- Add unit tests

When opening your PR, make sure to add some resulting visualizations.

**Comment by RiyazAina-DeepML** [comment]
NameError: name 'GradCAM' is not defined

**Comment by RaphaelMeudec** [comment]
@RiyazAina-DeepML Could you create a new issue and put some context in it? For example, a sample code to reproduce the error. Thanks
