### ISSUE TITLE
Explain Tabular 

### ISSUE THREAD

**Issue by cyrilledelabre** [sicara/tf-explain#78]
Hey, 
Amazing work!

However, it seems that your library only works for image related models.
Would it be possible to implement also the version for "tabular data" ? Indeed, original work on integrated gradients that you are using wasn't only reserved to image models (ie https://github.com/hiranumn/IntegratedGradients). It would be wonderful if your library could be also usable for non image related models since theory is not related to images only.

Thanks anyway for all the work done, it is really useful !

**Comment by RaphaelMeudec** [comment]
Hi @cyrilledelabre ! Indeed, to this day the library only supports images. It is in our head to extend to NLP soon. However, we do not plan to work on tabular data for now as there are already other libraries that are doing great work on the subject (Shap for example)

**Comment by cyrilledelabre** [comment]
Good to know that you will extend it to nlp ! 
Thanks for the answer ,
