### ISSUE TITLE
Heatmap display fails with rescaled image

### ISSUE THREAD

**Issue by transcranial** [sicara/tf-explain#95]
In the `heatmap_display` function, `original_image` is assumed to be [0, 255]. For GradCAM, when running `explain`, the original image is passed to the model as well as `heatmap_display`. However, if the model takes a rescaled input, such as [0, 1], then the output will not display the image since it's using the rescaled image.

In the GradCAM example, change [this line](https://github.com/sicara/tf-explain/blob/master/examples/core/grad_cam.py#L11) to:

```
img = tf.keras.preprocessing.image.img_to_array(img) / 255
```
and observe the output.

**Comment by RaphaelMeudec** [comment]
@transcranial Just merged a patch for this on master, should be good.

**Comment by rao208** [comment]
@RaphaelMeudec Could you please tell me what does this mean? I am using tensorflow 2.1. 

I still can't see the heatmap when the image is rescaled. I have a python file in which I do import tf_explain and Occlusion sensitivity callback.
